POST http://localhost:3004/api/users/
Content-Type: application/json 

  {
    "username": "test sunshine",
    "name": "sunshine",
    "password": "haha",
    "userId": "65f154e1597f60679a82bcad"
}

#   {
#     "username": "test rainny",
#     "name": "rainny",
#     "password": "rainny",
#     "userId": "65f154e1597f60679a82bcad"
#     "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QgcmFpbm55IiwiaWQiOiI2NjI3NzdiYzE3MTEyMTAzZjEyMWI1ZmIiLCJpYXQiOjE3MTM4NjI3MDYsImV4cCI6MTcxMzg2NjMwNn0.a41_mQlysKS5lS1cHogvuu0XGppSXUF-WoXoenTtbeY",

# }