POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "kakaka",
    "name": "Arina",
    "password": "kakaka1"
}
// username: kakaka, PW: kakaka1
// username: kaka, PW: kaka